# @format
services:
  # Redpanda Kafka broker with built-in schema registry
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr=internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr=internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr=internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr=internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr=redpanda:33145
      - --advertise-rpc-addr=redpanda:33145
      - --smp=1
      - --memory=1G
      - --mode=dev-container
      - --default-log-level=info
    ports:
      - "18081:18081" # Schema Registry
      - "18082:18082" # REST Proxy
      - "19092:19092" # Kafka API
      - "9644:9644" # Admin API
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    networks:
      - a2a-network
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -q 'healthy'"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redpanda Console for UI management
  console:
    image: redpandadata/console:latest
    container_name: redpanda-console
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
        schemaRegistry:
          enabled: true
          urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - "8080:8080"
    networks:
      - a2a-network
    depends_on:
      redpanda:
        condition: service_healthy

  # Agent 1: Task Requester
  agent-requester:
    build:
      context: .
      dockerfile: ./agents/Dockerfile
    container_name: agent-requester
    environment:
      - AGENT_TYPE=requester
      - AGENT_ID=agent-001
      - KAFKA_BROKER=redpanda:9092
      - SCHEMA_REGISTRY_URL=http://redpanda:8081
      - MCP_SERVER_PORT=8001
    ports:
      - "8001:8001"
    volumes:
      - ./schemas:/app/schemas
    networks:
      - a2a-network
    depends_on:
      redpanda:
        condition: service_healthy

  # Agent 2: Task Provider
  agent-provider:
    build:
      context: .
      dockerfile: ./agents/Dockerfile
    container_name: agent-provider
    environment:
      - AGENT_TYPE=provider
      - AGENT_ID=agent-002
      - KAFKA_BROKER=redpanda:9092
      - SCHEMA_REGISTRY_URL=http://redpanda:8081
      - MCP_SERVER_PORT=8002
    ports:
      - "8002:8002"
    volumes:
      - ./schemas:/app/schemas
    networks:
      - a2a-network
    depends_on:
      redpanda:
        condition: service_healthy

  # Agent 3: Task Executor
  agent-executor:
    build:
      context: .
      dockerfile: ./agents/Dockerfile
    container_name: agent-executor
    environment:
      - AGENT_TYPE=executor
      - AGENT_ID=agent-003
      - KAFKA_BROKER=redpanda:9092
      - SCHEMA_REGISTRY_URL=http://redpanda:8081
      - MCP_SERVER_PORT=8003
    ports:
      - "8003:8003"
    volumes:
      - ./schemas:/app/schemas
    networks:
      - a2a-network
    depends_on:
      redpanda:
        condition: service_healthy

volumes:
  redpanda_data:

networks:
  a2a-network:
    driver: bridge
